/* Generated By:JavaCC: Do not edit this line. AtomParserConstants.java */
package lcrf.logic.parser;

public interface AtomParserConstants {

    int EOF = 0;

    int VARIABLE = 2;

    int CONSTANT = 3;

    int STRING = 4;

    int NUMBER = 5;

    int COMMA = 6;

    int LPAREN = 7;

    int RPAREN = 8;

    int DEFAULT = 0;

    String[] tokenImage = { "<EOF>", "\" \"", "<VARIABLE>", "<CONSTANT>", "<STRING>", "<NUMBER>", "\",\"",
            "\"(\"", "\")\"", };

}
