package xprolog;

/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
public interface ParserConstants {

    int EOF = 0;

    int SINGLE_LINE_COMMENT = 6;

    int CUT = 7;

    int ADDOP = 8;

    int MULOP = 9;

    int RELOP = 10;

    int NUMBER = 11;

    int DIGIT = 12;

    int CHAR_LITERAL = 13;

    int VAR = 14;

    int ATOM = 15;

    int ANYCHAR = 16;

    int LOCASE = 17;

    int HICASE = 18;

    int DEFAULT = 0;

    String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "\"\\f\"",
            "<SINGLE_LINE_COMMENT>", "\"!\"", "<ADDOP>", "<MULOP>", "<RELOP>", "<NUMBER>", "<DIGIT>",
            "<CHAR_LITERAL>", "<VAR>", "<ATOM>", "<ANYCHAR>", "<LOCASE>", "<HICASE>", "\":-\"", "\".\"",
            "\":=\"", "\",\"", "\"(\"", "\")\"", "\"->\"", "\";\"", "\"[\"", "\"]\"", "\"|\"", };

}
