package xprolog;

//////////////////////////////////////////////////////
//
//  XProlog.java: the successor to Winikoff's WProlog
//  =================================================
//  Jean Vaucher
//  Email:  vaucher@iro.umontreal.ca
//  WWW:    www.iro.umontreal.ca/~vaucher/
// ------------------------------------------------------------------------
//  This work was carried out at CIRANO, the Center for Interuniversity
//  Research and Analysis on Organizations [www.cirano.qc.ca] during the
//  author's sabbatical year
// -----------------------------------------------------------------------
// 
//  This Prolog was developped to be used the handle the knowledge
//  and reasoning needs of Java based Agents.  It should be reasonably
//  fast and compact so that every agent could have its own KB and
//  inference engine.
//
//  Compared to several other "freeware" Prologs, WProlog turned out
//  to be remarkably fast.  However, it was weak in several areas:
//    - no assert/retract
//    - no arithmetic
//    - primitive syntax with no operators... not even the cut "!"
//    - it was wasteful of memory
//
//  Modifications:  Version 1.0  (april 2002)
//    - changed Parser to use one generated by JavaCC
//    - implemented the CUT (and "!" operator)
//    - added assert/retract
//    - added integer arithmetic:  +, -, *, /, mod
//      and comparisons:  ==, !=, >, <, >=, =<
//    - reduced memory use and improved running speed
//
// -----------------------------------------------------------------------
// WProlog : the original software by Michael Winikoff 
//           URL: http://goanna.cs.rmit.edu.au/~winikoff/wp/
//
// Version 1.0: 27/9/96 - 16/10/96
// Version 1.1: 20 January 1997
// Version 1.2:  2 April 1997
// Version 1.2.1: 19 August 1999 (fixed bug with unification of variable
//          to itself.
/////////////////////////////////////////////////////////////////
//  Benchmark results:  "path.pro" ==>   ?- solve(p(2,2),L).
//   started at 150 sec.
//    86 sec - Mac G4 with OsX & java 1.3.1
//    46 sec - Linux PC & java 1.3.1
// -------------------------------------------------------------
// May 6:  - added primitive "var(X)" 
//         - fixed "null reference" problem when backtracking to 
//             undefined predicate.
// -------------------------------------------------------------
// May 31:  - Added "sequences" to grammar, i.e.:  "  a,(b,c,d),x ,
//          - as well as IF and OR:
//     ...( a,b ; c,d,f )  ==> or([a,b],[c,d,f])
//     ...( tests -> true_part ; false_part )  ==>  if( [tests],[true_parft],[f_part])
// -------------------------------------------------------------
// To Do:
//   - handle commands when consulting files, i.e. print & consult
//   - check out behaviour for "not ( sequence of goals )"
//   - assert of rules (now is just facts)
//   - GET and SET

public class XProlog {

    public static void main(String args[]) {
        // insert code here...
        System.out.println("Hello World!");
    }

    public static String VERSION = "XProlog v.1.3, May 2002";
}
